### ISSUE TITLE
手机号的conf规则只配置VReg正则匹配,如果原始日志中手机号在json的末尾则没法匹配出来。

### ISSUE THREAD

**Issue by sunym1991** [bytedance/godlp#25]
1. 测试用例inStr := `2025-01-09 02:16:51,399 [http--exec-8] INFO  c.web.test.TestAction - [content]:{  "car_number"="沪CAG789", "email":"346824@qq.com","test":"ceshi_value","p":"18012341234"}}`
2. 结果：2025-01-09 02:16:51,399 [http--exec-8] INFO  c.web.test.TestAction  - [content]:{  "car_number"="沪C***89", "email":"3****@******","test":"ceshi_value","p":"18012341234"}}

**Comment by scofieldYang** [comment]
自己改源码吧，看样子这玩意都没人维护了

**Comment by wudihechao** [comment]
好好读默认配置文件里面的规则，改下配置文件就可以了
```` 
 # defaultRule start
  - RuleID: 1
    InfoType: PHONE
    Description: 手机号
    EnName: telephone_number
    CnName: 电话号码
    Level: L4
    # Detect feild is an array for detect methods, the relation of each item in detect is OR relation.
    # Regex: regex expression, no need to escape
    # KReg,VReg,KDict,VDict
    # Dict: [ word1, word2, ...],
    # (KReg || KDict) && (VReg || VDict)
    Detect:
      KReg: []
      KDict: []
      VReg:
        - 1(?:(((3[0-9])|(4[5-9])|(5[0-35-9])|(6[2,5-7])|(7[0135-8])|(8[0-9])|(9[0-35-9]))[ -]?\d{4}[ -]?\d{4})|((74)[ -]?[0-5]\d{3}[ -]?\d{4}))\b
      VDict: []
    # Filter contains blacklist.
    Filter:
      BAlgo: [MASKED] # supports MASKED, if detected value contains *, the result will not be returned
      BDict: [] # if one of results in blacklist dict, the result will not be returned.
      BReg: [] # blacklist regex list
    # Context: [word1, word2] one of context words has to be arround the result within ContextVerifyRange
    Verify:
      CDict: ["contact_phone", "remark_mobiles","ContactPhone", "phone","phones","number","telephone","telephones","cell","mobile","office","call","cellphone","cellphones","smartphone","smartphones","num","no","tel","linktel","contact","contactinfo","phoneno","phonenum","phonenumber","telephone_no","telephoneno","telephonenum","telephonenumber","mobilephoneno","mobliephonenum","mobilephonenumber","mobileno","moblieenum","mobilenumber","mobilecode","手机号","传真","手机","号码","联系","电话" ]
      CReg: []  # Regex list for context
      VAlgo: [] # value will be verified by verify function, such as IDCARD, 身份证校验函数
    Mask: CHINAPHONE # MaskRules.RuleName
    ExtInfo: # extra information, kv formate
      EnGroup: user_data
      CnGroup: 用户数据
````

Verify.CDict 下没有`p`，你这个正则匹配到了也不会被触发，你可以尝试把你的`p`改为`phoneno`或者，你在配置文件里把`p`加上
或者用这个规则
````
  - RuleID: 35
    InfoType: PHONE
    Description: 电话，kv类型
    EnName: telephone_number
    CnName: 电话号码
    Level: L4
    Detect:
      KDict: ["电话","投诉电话","mobile","phone"]
    Filter:
      BAlgo: [MASKED]
    Mask: PHONE
    ExtInfo: # extra information, kv formate
      EnGroup: user_data
      CnGroup: 用户数据
````
在这个规则里把Detect.KDict 里加上`p`
